# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b443898ecc5c2912c9b6fa9b90b512f7822dc222cb8c691187e03ae15f5ae4308bfe3ab6caee80667bccdf5454e23be7b224845b38a90e17ea0c2ec3024c61ca

test:
  secret_key_base: 614c8e89f7e7c9689f3b2256939b8167894b53e6d06552222e20280ae0b8c5c00cf998b8ea51c51a5fd8e6b6ed71a814bb0430f6034f0702030b8061ae9d988e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
